<?php
// DEBUG: Show all errors
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

header("Access-Control-Allow-Origin: *");
header("Content-Type: application/json; charset=UTF-8");

include_once '../../config/database.php';
include_once '../../models/TouristSpotCapacity.php';

$database = new Database();
$db = $database->getConnection();

$debug = [];
try {
    if ($db === null) {
        $debug[] = 'Database connection failed';
        throw new Exception("Database connection failed");
    }
    $tourist_spot_capacity = new TouristSpotCapacity($db);
    $town_id = isset($_GET['town_id']) ? intval($_GET['town_id']) : null;
    $debug[] = 'town_id: ' . var_export($town_id, true);
    $result = $tourist_spot_capacity->read($town_id);
    if (!$result) {
        $debug[] = 'read() returned false';
        throw new Exception($tourist_spot_capacity->getLastError() ?? "Failed to read tourist spot capacity data");
    }
    $num = $result->num_rows;
    $debug[] = 'num_rows: ' . $num;
    if ($num > 0) {
        $records = array();
        while ($row = $result->fetch_assoc()) {
            $record = array(
                "capacity_id" => $row['capacity_id'] ?? null,
                "spot_id" => $row['spot_id'],
                "name" => $row['name'],
                "category" => $row['category'],
                "town_name" => $row['town_name'],
                "current_capacity" => intval($row['current_capacity'] ?? 0),
                "max_capacity" => intval($row['max_capacity'] ?? 0),
                "capacity_percentage" => floatval($row['capacity_percentage'] ?? 0),
                "last_updated" => $row['last_updated'],
                "updated_by" => $row['updated_by_user']
            );
            $records[] = $record;
        }
        echo json_encode([
            "success" => true,
            "records" => $records,
            "count" => $num,
            "debug" => $debug
        ]);
    } else {
        echo json_encode([
            "success" => true,
            "records" => [],
            "count" => 0,
            "message" => "No tourist spot capacity records found",
            "debug" => $debug
        ]);
    }
} catch (Exception $e) {
    http_response_code(500);
    echo json_encode([
        "success" => false,
        "message" => $e->getMessage(),
        "debug" => $debug
    ]);
}
// Always output something
if (!headers_sent() && ob_get_length() === 0) {
    echo json_encode([
        "success" => false,
        "message" => "No output generated by script.",
        "debug" => $debug
    ]);
}