<?php
// DEBUG: Show all errors
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

header("Access-Control-Allow-Origin: *");
header("Content-Type: application/json; charset=UTF-8");
header("Access-Control-Allow-Methods: POST");
header("Access-Control-Max-Age: 3600");
header("Access-Control-Allow-Headers: Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With");

include_once '../../config/Database.php';
include_once '../../models/TouristSpotCapacity.php';

$database = new Database();
$db = $database->getConnection();

$debug = [];
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}
if (isset($_SESSION['user_type_id']) && $_SESSION['user_type_id'] == 1) {
    http_response_code(403);
    echo json_encode([
        'success' => false,
        'message' => 'Forbidden: Super Admin accounts cannot modify tourist spot capacity.',
        'debug' => $debug
    ]);
    exit();
}

// If Tourism Officer, ensure the spot belongs to their municipality
if (isset($_SESSION['user_type_id']) && $_SESSION['user_type_id'] == 3) {
    $officer_town = $_SESSION['town_id'] ?? null;
    $raw = file_get_contents('php://input');
    $payload = json_decode($raw, true);
    $spot_id_check = $payload['spot_id'] ?? null;
    $debug[] = 'officer_town: ' . var_export($officer_town, true);
    $debug[] = 'spot_id_check: ' . var_export($spot_id_check, true);
    if ($spot_id_check && $officer_town) {
        $stmtCheck = $db->prepare("SELECT town_id FROM tourist_spots WHERE spot_id = ? LIMIT 1");
        $stmtCheck->bind_param('i', $spot_id_check);
        $stmtCheck->execute();
        $res = $stmtCheck->get_result();
        $row = $res->fetch_assoc();
        if (!$row || strval($row['town_id']) !== strval($officer_town)) {
            http_response_code(403);
            echo json_encode(['success' => false, 'message' => 'Forbidden: You do not have permission to modify capacity for this spot.', 'debug' => $debug]);
            exit();
        }
    }
}

$capacity = new TouristSpotCapacity($db);
$data = json_decode(file_get_contents("php://input"));
$errors = array();

if (empty($data->spot_id)) {
    $errors[] = "Tourist spot ID is required";
}
if (!isset($data->current_capacity)) {
    $errors[] = "Current capacity is required";
}
if (empty($data->max_capacity)) {
    $errors[] = "Maximum capacity is required";
}

if (empty($errors)) {
    if (!is_numeric($data->current_capacity) || !is_numeric($data->max_capacity)) {
        $errors[] = "Capacity values must be numbers";
    } else {
        if ($data->current_capacity < 0) {
            $errors[] = "Current capacity cannot be negative";
        }
        if ($data->max_capacity <= 0) {
            $errors[] = "Maximum capacity must be greater than 0";
        }
        if ($data->current_capacity > $data->max_capacity) {
            $errors[] = "Current capacity cannot exceed maximum capacity";
        }
    }
}

if (!empty($errors)) {
    http_response_code(400);
    echo json_encode(array(
        "success" => false, 
        "message" => "Validation failed", 
        "errors" => $errors,
        "debug" => $debug
    ));
    exit;
}

$capacity->spot_id = $data->spot_id;
$capacity->current_capacity = $data->current_capacity;
$capacity->max_capacity = $data->max_capacity;
$capacity->updated_by = isset($_SESSION['user_id']) ? $_SESSION['user_id'] : 1;
if ($capacity->update()) {
    $percentage = ($capacity->current_capacity / $capacity->max_capacity) * 100;
    http_response_code(200);
    echo json_encode(array(
        "success" => true,
        "message" => "Tourist spot capacity was updated successfully",
        "data" => array(
            "spot_id" => $capacity->spot_id,
            "current_capacity" => $capacity->current_capacity,
            "max_capacity" => $capacity->max_capacity,
            "capacity_percentage" => round($percentage, 1),
            "last_updated" => date('Y-m-d H:i:s')
        ),
        "debug" => $debug
    ));
} else {
    http_response_code(503);
    echo json_encode(array(
        "success" => false, 
        "message" => "Database error: Unable to update tourist spot capacity",
        "error_details" => $capacity->getLastError(),
        "debug" => $debug
    ));
}

// Always output something
if (!headers_sent() && ob_get_length() === 0) {
    echo json_encode([
        "success" => false,
        "message" => "No output generated by script.",
        "debug" => $debug
    ]);
}
